@startuml
start
:Ověřit existenci žáka;
:Ověřit existenci třídy;
:Ověřit existenci podskupiny;
if (Žák přiřazen k podskupině?) then (ano)
  :Ukončit aktuální přiřazení k podskupině;
  :Přiřadit žáka do nové podskupiny;
  :Aktualizovat databázi;
else (ne)
  :Zobrazit chybovou zprávu;
endif
stop
@enduml
