@startuml
entity "Class" as C {
  classId : int
  letter : string
  prefix : string
  validFrom : Datetime
  validTo : Datetime
  roomId : int
  employeeId : int
}

entity "SubClass" as SC {
  * subClassId : int
  --
  classId : int
  name : string
}

entity "Student" as S {
  * studentId : int
  --
  username : string
  name : string
  surname : string
}

entity "StudentAssignment" as SA {
  * assignmentId : int
  --
  studentId : int
  classId : int
  subClassId : int
}

C ||--o{ SC : contains
C ||--o{ SA : contains
SC ||--o{ SA : contains
S ||--o{ SA : has
@enduml