@startuml
entity "Class" as Class {
    +classId: int
    +letter: string
    +prefix: string
    +validFrom: Datetime
    +validTo: Datetime
    +roomId: int
    +employeeId: int
}

entity "SubClass" as SubClass {
    +subClassId: int
    +classId: int
    +name: string
}

entity "Student" as Student {
    +studentId: int
    +username: string
    +name: string
    +surname: string
}

entity "Student Assignment" as StudentAssignment {
    +studentId: int
    +classId: int
    +subClassId: int
}

Class ||--o{ SubClass : "contains"
Class ||-left-o{ StudentAssignment : "contains"
SubClass ||--o{ StudentAssignment : "contains"
Student ||-right-o{ StudentAssignment : "has"

@enduml