@startuml ed-schedule-calculated-previous-relation
entity "Student" as Student {
    +id: int
    +name: string
    +surname: string
    +valid_to: date
}

entity "Class" as Class {
    +prefix: string
    +sufix: string
    +creation_date: date
}


Student ||--o{ Student : "previous accounts"

Class ||--o{ Student : "contains"

@enduml
