@startuml ed-schedule-calculated-class
entity "Class" as Class {
    +prefix: string
    +suffix: string
    +creation_date: date
}

entity "Student" as Student {
    class_id: int
}

entity "LessonRecord" as LessonRecord {
}

entity "Absence" as Absence {
}

Class ||--o{ Student : "contains"

Student ||--o{ Absence : "has absence"
Student ||--o{ LessonRecord : "has lesson record"

LessonRecord ||-{ Absence : "contains records of student's absence"

@enduml