@startuml ed-schedule-calculated-study-entity
entity "Student" as Student {
    + student_id: int
}

entity "Study" as Study {
    + study_id: int
    + student_id: int
    + class_id: int
    + schoolyear_id: int
}

entity "Class" as Class {
    + class_id: int
    + prefix: string
    + suffix: string
    + creation_date: date
}

entity "SchoolYear" as SchoolYear {
    + schoolyear_id: int
    + name: string
}

Student ||-left-o{ Study : "has"
Class ||-o{ Study : "belongs to"
Study }o-up-|| SchoolYear : "is in"
@enduml